apiVersion: batch/v1
kind: Job
metadata:
  name: sql-migrations
spec:
  template:
    spec:
      initContainers:
        - name: loading-sql-scripts
          image: k8s.gcr.io/git-sync/git-sync:v3.2.2
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/toporischev/otus-sql
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_ROOT
              value: /flyway/sql
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          volumeMounts:
            - name: sql
              mountPath: /flyway/sql
      containers:
        - name: sql-migrations
          image: flyway/flyway
          args:
            - info
            - migrate
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres/otus
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: sql-migrations-secrets
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-migrations-secrets
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_LOCATIONS
              value: filesystem:/flyway/sql/otus-sql/sql
          volumeMounts:
            - name: sql
              mountPath: /flyway/sql
      volumes:
        - name: sql
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 2
