apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
    - image: toporischev/lesson6.user-service
      context: ../UserService
deploy:
  helm:
    releases:
      - name: user-skaffold
        chartPath: user-chart
        artifactOverrides:
          image: toporischev/lesson6.user-service
