apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_URI: {{ .Values.postgres.uri }}
  POSTGRES_DB: {{ .Values.postgres.db }}

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
