apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}
spec:
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: ClusterIP
